### ISSUE TITLE
make a solver option for runtests

### ISSUE THREAD

**Issue by chriscoey** [mlubin/JuGP.jl#10]

**Comment by IainNZ** [comment]
Might want to use the style from JuMP, and JuMPeR, of iterating over the solvers - JuMPeR just uses JuMP's `test/solvers.jl` file directly since JuMP is always installed (as is the case here).

**Comment by mlubin** [comment]
Yeah, that's what we'll do

**Comment by mlubin** [comment]
After https://github.com/mlubin/JuGP.jl/pull/18 the tests now let you loop over solvers
