### ISSUE TITLE
method error for *(::JuGP.Monomial, ::JuGP.Posynomial)

### ISSUE THREAD

**Issue by chriscoey** [mlubin/JuGP.jl#5]
> Got an exception of type MethodError outside of a @test
>   MethodError: `*` has no method matching *(::JuGP.Monomial, ::JuGP.Posynomial)
>   Closest candidates are:
>     *(::Any, ::Any, !Matched::Any, !Matched::Any...)
>     *(::JuGP.Monomial, !Matched::JuGP.Monomial)
>     *(!Matched::Number, ::JuGP.Posynomial)
>    in _mapreduce at reduce.jl:145
>    in mapreduce at reduce.jl:159
>    in mapreduce at reduce.jl:162
>    in descend at /Users/chris/.julia/v0.4/JuGP/src/expr.jl:29
>    in descend at /Users/chris/.julia/v0.4/JuGP/src/expr.jl:23 (repeats 2 times)
>    in check_expr_gp at /Users/chris/.julia/v0.4/JuGP/src/expr.jl:35
>    in loadproblem! at /Users/chris/.julia/v0.4/JuGP/src/solver.jl:46
>    in _buildInternalModel_nlp at /Users/chris/.julia/v0.4/JuMP/src/nlp.jl:1189
>    in buildInternalModel at /Users/chris/.julia/v0.4/JuMP/src/solvers.jl:307
>    in solve at /Users/chris/.julia/v0.4/JuMP/src/solvers.jl:131
>    [inlined code] from /Users/chris/.julia/v0.4/JuGP/test/runtests.jl:216
>    in anonymous at no file:0
>    in include at /Applications/Julia-0.4.3.app/Contents/Resources/julia/lib/julia/sys.dylib
>    in include_from_node1 at /Applications/Julia-0.4.3.app/Contents/Resources/julia/lib/julia/sys.dylib
>    in process_options at /Applications/Julia-0.4.3.app/Contents/Resources/julia/lib/julia/sys.dylib
>    in _start at /Applications/Julia-0.4.3.app/Contents/Resources/julia/lib/julia/sys.dylib

code:

```
    a     = ones(7)
    alpha = ones(7)
    beta  = ones(7)
    gamma = ones(7)
    f = [1, 0.8, 1, 0.7, 0.7, 0.5, 0.5]
    e = [1, 2, 1, 1.5, 1.5, 1, 2]
    Cout6 = 10
    Cout7 = 10

    m = Model(solver=GPSolver())

    @defVar(m, D)

    @defVar(m, x[i=1:7] >= 1) #, Int) # optional: require integer gate sizes

    @setNLObjective(m, Min, D)

    @defNLExpr(m, C[i=1:7], alpha[i] + beta[i] * x[i])
    @defNLExpr(m, A, sum{a[i] * x[i], i=1:7})
    @defNLExpr(m, P, sum{f[i] * e[i] * x[i], i=1:7})
    @defNLExpr(m, R[i=1:7], gamma[i] / x[i])
    @defNLExpr(m, D1, R[1] * C[4])
    @defNLExpr(m, D2, R[2] * (C[4] + C[5]))
    @defNLExpr(m, D3, R[3] * (C[5] + C[7]))
    @defNLExpr(m, D4, R[4] * (C[6] + C[7]))
    @defNLExpr(m, D5, R[5] * C[7])
    @defNLExpr(m, D6, R[6] * Cout6)
    @defNLExpr(m, D7, R[7] * Cout7)

    @addNLConstraint(m, P <= 20)
    @addNLConstraint(m, A <= 100)
    @addNLConstraint(m, D1+D4+D6 <= D)
    @addNLConstraint(m, D1+D4+D7 <= D)
    @addNLConstraint(m, D2+D4+D6 <= D)
    @addNLConstraint(m, D2+D4+D7 <= D)
    @addNLConstraint(m, D2+D5+D7 <= D)
    @addNLConstraint(m, D3+D5+D6 <= D)
    @addNLConstraint(m, D3+D7 <= D)

    # test continuous problem
    status = solve(m)
    @test status == :Optimal
    # comparing optimal continuous answers with YALMIP solutions
    x_opt = [1.9563, 3.1588, 3.0455, 3.3454, 1.6713, 3.1224, 3.1155]
    for i=1:7
        @test_approx_eq_eps getValue(x[i]) x_opt[i] 1e-2
    end
    @test_approx_eq_eps getObjectiveValue(m) 7.8936 1e-2
```

**Comment by mlubin** [comment]
Tested the code and it seems to work now
